#!/bin/bash
C(){ for((i=0;i<=n;i++));do let $1[i]=$2[i];done }
S(){ for((i=1;i<=n;i++));do let $1[i++]=0;done;let $1[0]=$2;}
M(){ c=0;for((i=n;i>=0;i--));do let r=$1[i]*${2}+c c=r/b r%=b $1[i]=r;done }
D(){ c=0;for((i=0;i<=n;i++));do let r=$1[i]+c*b c=r%$2 r/=$2 $1[i]=r;done }
n=$((${1:-72}/4+1));b=10000;A t x y 5;A z x y 239;M t 4;L t z;M t 4
printf ${t[0]}.;for((i=1;i<n;i++));do printf "%04d" ${t[i]};done;echo
